"""fixed unique constraints on comments/posts/users

Revision ID: 8f86f2c2c772
Revises: 7ea3102aff16
Create Date: 2021-02-22 18:09:01.453595

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8f86f2c2c772'
down_revision = '7ea3102aff16'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('comments_postId_key', 'comments', type_='unique')
    op.drop_constraint('comments_userId_key', 'comments', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('comments_userId_key', 'comments', ['userId'])
    op.create_unique_constraint('comments_postId_key', 'comments', ['postId'])
    # ### end Alembic commands ###
