"""fixed unique constraint on posts/users

Revision ID: 7ea3102aff16
Revises: 4897b529a7c2
Create Date: 2021-02-22 18:01:59.609362

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7ea3102aff16'
down_revision = '4897b529a7c2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('posts_userId_key', 'posts', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('posts_userId_key', 'posts', ['userId'])
    # ### end Alembic commands ###
